spring:
  application:
    name: premium-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://trangiangkhanh.online:5432/sba_premium_db
    username: devsba301
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka:123456@localhost:8761/eureka

server:
  port: '8807'