spring:
  application:
    name: personality-chat-ai-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://trangiangkhanh.online:5432/ChatAI_DB
    username: devsba301
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  ai:
    gemini:
      api-key: ${GEMINI_API_KEY:AIzaSyAcmMJeavWAS6k8BI3thSXQgH86jJatO80}
      base-url: https://generativelanguage.googleapis.com/v1beta/models

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:123456@localhost:8761/eureka
  enabled: false

server:
#  servlet:
#    context-path: /ai
  port: 8810

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

#logging:
#  level:
#    com.quizservice: DEBUG
#    org.springframework.web: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics
