eureka:
  client:
    service-url:
      defaultZone: http://eureka:123456@localhost:8761/eureka

spring:
  application:
    name: auth-service

  main:
    banner-mode: off

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://ep-mute-sunset-a8vgkfvy-pooler.eastus2.azure.neon.tech/Authentication
#    username: Authentication_owner
#    password: npg_b05PxiXjfWtL
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://trangiangkhanh.online:5432/authentication
    username: devsba301
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    function:
      definition: profileCreationFailed
    stream:
      bindings:
        sendNotification-out-0:
          destination: notification-delivery
        sendUserCreated-out-0:
          destination: user-created-topic
        profileCreationFailed-in-0:
          destination: profile-creation-failed-topic
      kafka:
        binder:
          brokers: localhost:9094

outbound:
  identity:
    client-id: "1010429030946-7rpjhtpauni9gim1ihfrbjeh79d21ddc.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "http://localhost:5173/authenticate"

server:
  port: 8801

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
