spring:
  application:
    name: university-service
  data:
    mongodb:
      uri: mongodb://mongo:123456@trangiangkhanh.online:27017/university_service?authSource=admin&authMechanism=SCRAM-SHA-1
      database: university_service
server:
  port: '8805'
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
eureka:
  client:
    service-url:
      defaultZone: http://eureka:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
