spring:
  application:
    name: persona-service
  cloud:
    stream:
      bindings:
        userCreated-in-0:
          destination: user-created-topic
        profileCreationFailed-out-0:
          destination: profile-creation-failed-topic
      kafka:
        binder:
          brokers: localhost:9094

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://trangiangkhanh.online:5432/persona
    username: devsba301
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka:123456@localhost:8761/eureka

server:
  port: '8804'

springdoc:
  api-docs:
    path: /api-docs