CREATE DATABASE order_v1;

-- ENUM cho trạng thái đơn hàng
CREATE TYPE order_status AS ENUM ('PENDING', 'COMPLETED', 'CANCELLED');

-- ENUM cho loại item
CREATE TYPE item_type AS ENUM ('PREMIUM', 'TICKET');

CREATE TABLE orders (
                        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        time TIMESTAMP NOT NULL,
                        total DOUBLE PRECISION NOT NULL,
                    --    status order_status NOT NULL,
                        status VARCHAR(100) NOT NULL,
                        user_id VARCHAR(100) NOT NULL
);

CREATE TABLE order_item (
                             id SERIAL PRIMARY KEY,
                             item_id INTEGER NOT NULL,
                             quantity INTEGER NOT NULL,
--                              item_type item_type NOT NULL,
                             item_type VARCHAR NOT NULL,
                             order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE
);

INSERT INTO orders (id, time, total, status)
VALUES
    (1, NOW(), 150.00, 'PENDING'),
    ( 2, NOW(), 230.50, 'COMPLETED');


INSERT INTO order_item (item_id, quantity, item_type, order_id)
VALUES
    (101, 2,  'PREMIUM', 1),
    (202, 1,  'TICKET', 1),
    (203, 3,  'TICKET', 2);
