eureka:
  client:
    service-url:
      defaultZone: http://eureka:123456@localhost:8761/eureka

spring:
  application:
    name: quiz-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://trangiangkhanh.online:5432/QuizDB
    username: devsba301
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: "8803"

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
#logging:
#  level:
#    com.quizservice: DEBUG
#    org.springframework.web: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics

